### ISSUE TITLE
You should switch the frontend to use Invidious, so it doesn't require API keys.

### ISSUE THREAD

**Issue by R3n001** [CrazyFrogEpic/Late-2012-YT-Frontend#1]
I hosted this frontend for some friends, and the API key ran out in less than 15 minutes.

**Comment by SoulRepo** [comment]
Planning to do that with my fork.

**Comment by CrazyFrogEpic** [comment]
hello, sorry it took so long to respond. the invidious api has been added, and api keys are no longer required.
