### ISSUE TITLE
Frontend appears to be broken.

### ISSUE THREAD

**Issue by R3n001** [CrazyFrogEpic/Late-2012-YT-Frontend#2]
On my hosted instance, video pages cause a few php errors, and nothing really loads.

**Comment by CrazyFrogEpic** [comment]
not broken, you need to replace the api domains every so often when that happens.
http://api.invidious.io

**Comment by R3n001** [comment]
> 
> 
> not broken, you need to replace the api domains every so often when that happens.
> http://api.invidious.io

How would I go about doing that?

**Comment by R3n001** [comment]
I noticed you have a url with a much more advanced version of this, when will this be pushed to GitHub?

**Comment by R3n001** [comment]
Magically fixed itself.
